### ISSUE TITLE
Deploy Website hangs and fails with timeout

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#2861]
## Where to find the issue

https://github.com/corona-warn-app/cwa-website/blob/master/.github/workflows/deploy-master.yml

## Describe the issue

https://github.com/corona-warn-app/cwa-website/blob/master/.github/workflows/deploy-master.yml scheduled to run as follows:

```
schedule:
    - cron: '0 11 * * *'
    - cron: '0 17 * * *'
```

ultimately fails with the error 

`The job running on runner Hosted Agent has exceeded the maximum execution time of 360 minutes`

https://github.com/corona-warn-app/cwa-website/actions/runs/2290301030 

started Sun, 08 May 2022 17:13:04 GMT
then on Sun, 08 May 2022 23:13:14 GMT the log file shows
`Error: The operation was canceled.`

after 6 hours of running.

https://github.com/corona-warn-app/cwa-website/actions/runs/2293795587

started Mon, 09 May 2022 11:17:26 GMT
It is currently 15:16 UTC, so the job has been running for 4 hours already. It is hung in the "Deploy master" section.

---
Internal Tracking ID: [EXPOSUREAPP-13073](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13073)

**Comment by Ein-Tim** [comment]
Please also share the results of your investigation on this issue here.

**Comment by MikeMcC399** [comment]
Also regular deployments following a pull request are affected, not just the scheduled deployments.
See https://github.com/corona-warn-app/cwa-website/runs/6367451651 which hung and was then manually cancelled.

**Comment by dsarkar** [comment]
Fixed. Credits go to @svengabr, who might give you more details. At the same time upload time is reduced from about 8-9 min to about 15 seconds, depending on the amount of files that have changed. With this fix a "sync" takes place, i.e. only changed files are uploaded.

**Comment by MikeMcC399** [comment]
@dsarkar 

> Fixed. 🎉 !

I will wait to check that the scheduled Deploy also works. The next one is planned for 17:00 GMT => 19:00 CEST.

**Comment by MikeMcC399** [comment]
https://www.coronawarn.app/en/analysis/ displays no data

**Comment by MikeMcC399** [comment]
FAQ search does not work on https://www.coronawarn.app/en/faq/ or on https://www.coronawarn.app/en/faq/results/

**Comment by Ein-Tim** [comment]
@MikeMcC399 I vote for opening a new issue for the problems which occur now.
Or is the root cause still the same (e.g. the log of the deployment action still shows the same issue)?

**Comment by MikeMcC399** [comment]
@Ein-Tim 

>  I vote for opening a new issue for the problems which occur now. Or is the root cause still the same (e.g. the log of the deployment action still shows the same issue)?

Thank you for your suggestion. I will open a new issue. I suspect it is due to the changed deployment and it looks like it might be a permissions issue.

**Comment by MikeMcC399** [comment]
- See also https://github.com/corona-warn-app/cwa-website/issues/2870

**Comment by Ein-Tim** [comment]
Thanks Mike! 👍

**Comment by MikeMcC399** [comment]
Deployment no longer hangs, so closing this issue.

- There are however major issues remaining, which have been reported in #2870
