### ISSUE TITLE
FAQ: Corrections needed to update of "[Apple/iOS]: ENErrorDomain-Error 13"

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#715]
## Where to find the issue
"[Apple/iOS]: ENErrorDomain-Error 13" https://www.coronawarn.app/en/faq/#ENError13
"[Apple/iOS]: ENErrorDomain-Fehler 13" https://www.coronawarn.app/de/faq/#ENError13

## Describe the issue
1. Both the English and the German error messages are included in the [English FAQ](https://www.coronawarn.app/en/faq/#ENError13) and [German FAQ](https://www.coronawarn.app/de/faq/#ENError13).
2. The English error message in the English FAQ is incorrect.

## Suggested change
FAO @dsarkar & @loki-cui 

In https://www.coronawarn.app/en/faq/#ENError13 (English version of FAQ)
- Remove the text "German error message: "Fehler 13: Ihre Risiko-Ermittlung für den heutigen Tag wurde bereits durchgeführt. Bitte versuchen Sie es in 24 Stunden erneut.""
- Remove the text "English error message:"
- Change the text of the English error message to "Error 13: Your exposure logging for today has already been carried out. Please try again in 24 hours." to correspond to the requested text in the original issue in https://github.com/corona-warn-app/cwa-website/issues/713.

In https://www.coronawarn.app/de/faq/#ENError13 (German version of FAQ)
- Remove the text "Deutsche Fehlermeldung:"
- Remove the text "Englische Fehlermeldung: "Error 13: Your exposure logging for today has already been carried out. Please try again in 24 hours."

**Comment by dsarkar** [comment]
@MikeMcC399, thanks. Will correct English the error message. Having both messages, in English and German in both FAQ entries might help the users to find. What´s your thought on this? Thanks, DS

**Comment by MikeMcC399** [comment]
@dsarkar 
>Will correct English the error message. 

Thank you!

>Having both messages, in English and German in both FAQ entries might help the users to find. What´s your thought on this? 

The disadvantages outweigh any benefits. Including both language error messages in each language:

- makes each article longer to read
- makes this FAQ entry different from every other FAQ entry
- may be irritating to readers who only understand English or only understand German

So I would still suggest keeping to one language in each article and removing the other language in each article.

**Comment by heinezen** [comment]
Fixed in #719

**Comment by MikeMcC399** [comment]
@heinezen 
Could you please check, because there are 0 files changed in
https://github.com/corona-warn-app/cwa-website/pull/719

and I can't see any change on https://www.coronawarn.app/en/faq/#ENError13 either.

**Comment by dsarkar** [comment]
@MikeMcC399, ok, agreed.

**Comment by MikeMcC399** [comment]
@heinezen / @dsarkar 
The English error message in https://www.coronawarn.app/en/faq/#ENError13 is still incorrectly rendered as:
"Error 13: Your exposure **to** today has already been carried out. Please try again in 24 hours."

whereas, according to the original post https://github.com/corona-warn-app/cwa-website/issues/713 it should be:
"Error 13: Your exposure **logging for** today has already been carried out. Please try again in 24 hours."
